### ISSUE TITLE
Add basic dashboard page

### ISSUE THREAD

**Issue by begizi** [mojotech/standup-client#21]
Should serve as en entry point to jump into projects.

The trello dashboard should serve as a decent reference point for the purpose and structure of the dashboard page.

**Comment by mordecai174** [comment]
@begizi do we need this view if we have that dropdown to switch projects?

**Comment by begizi** [comment]
I think so. We can probably do something like pivotal tracker does and have the landing page be whatever your last open project was, but we need a nice way to view all of your projects and a landing page for new/returning users. I think [http://trello.com](http://trello.com) and [https://www.pivotaltracker.com/dashboard](https://www.pivotaltracker.com/dashboard) are good examples of what we need for a dashboard/landing page.

**Comment by mordecai174** [comment]
so we can't jsut default to the last opened project? then you just switch via the dropdown? is this for someone who logs out, then back in?

**Comment by begizi** [comment]
I think a dashboard is necessary for the following reasons:

1. Gives a landing page to new users who don't have any projects their associated with.
2. Gives us a platform to add aggregate project information so a PM or person with multiple projects can manually navigate to the dashboard to see a high level overview of all their projects.
3. Gives us a landing page for users who don't have a last viewed project. (Gives us the option to store that data locally in the browser so we don't have to worry about storing that state in the database when it's really only a concern of the client)

Opening to the last opened project is a useful feature, but I don't think we should be dependent on it as our landing page. It should be a feature addition built on top of a stable user flow.

**Comment by mordecai174** [comment]
we don't need to go further with it, i see value in it, not sure I understand your points completely, but if you guys think we need it now, im all for it.

1. how would this happen? On signup they could create a project?
2. at a project level i get this. are you thinking like # of each entry type?
3. not sure i know what this means, seems like # 1? if everyone has at least one project, they would always have a place to land, no?

**Comment by begizi** [comment]
1. When a user signs up for the service for the first time they aren't on any projects so we wouldn't have anywhere to start after the logged in.
2. I'm thinking we could show things like # of each status (complete, in progress, blocked), which users have written a standup for today, and maybe project meta like when the standup is scheduled for, project description (can contain information about how to join the call, links, etc.)
3. This depends on how we implement this feature. My preference is to store the last viewed project on the client browser since it's a client concern and the server shouldn't care about what project they last looked at. But if we do that then we will need a landing page for a case when the user logs in from a new browser or if their local storage gets cleared and we no longer have a default project to load.
