### ISSUE TITLE
Add Task Status Editing

### ISSUE THREAD

**Issue by begizi** [mojotech/standup-client#43]
![](http://d.pr/i/11dvE+)

**Comment by katrynmc** [comment]
@begizi Add a key or hover tooltip to the status options? I didn't know what the colors meant.

**Comment by katrynmc** [comment]
^ This may be a completely separate issue but I figured I'd raise the question here first

**Comment by begizi** [comment]
Yea. I'll open up a new task to add tooltips. Would you want to contribute that @katrynmc?

**Comment by katrynmc** [comment]
@begizi Actually yeah! I would be totally down for that. I'll get started next mojo time :dancer:

**Comment by begizi** [comment]
Closed by #71
